---
authors:
  - Jakob Meng (https://github.com/jm1)
dependencies:
  "jm1.libvirt": '>=2024.5.30'
  "jm1.pkg": '>=2024.5.30'
  "jm1.openstack": '>=2024.5.30'
description: null
documentation: https://github.com/jm1/ansible-collection-jm1-packages/tree/master/docs
homepage: https://github.com/jm1/ansible-collection-jm1-packages
issues: https://github.com/jm1/ansible-collection-jm1-packages/issues
#license: GPL-3.0-or-later
license_file: LICENSE.md
name: packages
namespace: jm1
readme: README.md
repository: https://github.com/jm1/ansible-collection-jm1-packages
tags: null
version: 2023.2.22
