---
# Copyright (c) 2020-2021 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

- name: Add apt key for Launchpad PPA Ansible by Ansible, Inc.
  ansible.builtin.apt_key:
    data: |
      -----BEGIN PGP PUBLIC KEY BLOCK-----

      xsFNBFOXbTABEADKLcY3MYZyHIiCEu8cQ+0UzxZolTYZf8xZ06/d8xzUW/UBPTLV
      x/40IzWJEZU87GCYVXUhdYXECrFQKQOOEWQswBxOt26/g0nIrU0edZ9cCZ9o9+ZO
      sKDcScWNxWeclLr2+YHdmX9eph+2p+zIPmhNJaaWV6/bSo1fBi7ganZFRAc13zO8
      jtQsYyIeoAFwjt1vbk9CifdFhEchRVbwvZYhZDWfBZjhZ15UOunjo47gEkpK0PsW
      HY5N3/c75pGMwMTCjHMKno6KFzhdKLaz/QgbNnpy1aMkA/LITeU6Pgg6iqofrSY3
      Fx73MCAb8EEytvSV/65wztKzexHjGYxhm5ygoET5tPyXciX0+XzojkZAHzUEeT5z
      4kgL6OLyn+JQAyRDNnOJEkYmvwQveZuUjsYUkgc5DJdg6w7lTgQHWObOENpXls3B
      DnphA4DJyc0PQODCxdSZo4ZXMLn5lE/0qvAJ6g/wntY/ee/vRKwy9iDMOWQvihTI
      Y/L70/TnE4qZdaNbOJEvW59LT6GBTrcU1MX2fS5hU/mQa2CNixSVZG98rba3tfNa
      LDDNqivkcxtWryEWd0giBzzUS+MhtxhHm77YgxNVyyFn8bXb25/W+Jq+VvWWx2KD
      3ZwVD37X8wIBRLVozoH0jHVW7jKTnf2z+D6FCM+pVlm8zV1upXbHbdaRqwARAQAB
      zR9MYXVuY2hwYWQgUFBBIGZvciBBbnNpYmxlLCBJbmMuwsF4BBMBAgAiBQJTl20w
      AhsDBgsJCAcDAgYVCAIJCgsEFgIDAQIeAQIXgAAKCRCTxKP9e7nDZwzdD/9yFq+3
      ptLyWP1JN3RXsvTIJLhhjOqMMJCOocV0G3slHeUtdIDmvd2RaS8PeFNSd9QFbUzk
      a7pBXec3a7kgEVorty2/+cZSpEVHT26oAbJnoH7E1YGii8bbnk9LqOCF/nLpasEq
      PKqtVzXz+vGB7G0ox8qmRm6JynrMeLBftYemxJ8e4fii6APJxE6FPz/AvgcN3BtB
      guseFwcga6lGcmp0JLofGhTbejfS9dW9bnCFJBtRfzUVd+Cb8aYuzV5zgCJgqOBJ
      Hf0L6xDwn8UuzRfi0MWzEskuC/KxUJqVHMuTaLdrSeP1/czompetbsSHTfDklf/p
      4EbSM9VqZFiKr17we0LdigAEv2JnL2Qj0oN3eRNU0sDJ3kZvh5qhnteNgSRM/el0
      Sly+34CRZzX25vd+pOTgwK6VFx3wvWfqn3pVNT9ASNalhogFXuBY2ukYJaiUTPsS
      R4+KHiD3eIhWyayBGP+GRvGb5dVC29k4CjLvQM9lISmZrrxGmMGoV9S1dh7siZYE
      CaVW0nKI95d6bBHaKH1g5HJ7NEsVTwf8LRY/FFpLsEPVw4HNVqqqwhuJnSW70WQ3
      blh0RIX/+z9hAla+M0kix7r0lS89ZBdTgwPuiCrkPRpoxi06ah/Q62uP3ZN4+dew
      1sBZdaC9kaKdOOWTqArVnaPObQgUUJFhY9wUsA==
      =uKv4
      -----END PGP PUBLIC KEY BLOCK-----
    keyring: /etc/apt/trusted.gpg.d/launchpad-ppa-ansible-ansible.gpg
    # Use ascii key instead of keyserver because receiving keys from keyserver.ubuntu.com fails with a timeout or
    # error message "gpg: keyserver receive failed: Server indicated a failure". This bug might be related to
    # https://dev.gnupg.org/T2889 or https://bbs.archlinux.org/viewtopic.php?id=259473
    #
    #id: 93C4A3FD7BB9C367
    #keyserver: keyserver.ubuntu.com

- name: Add apt repository of Launchpad PPA Ansible by Ansible, Inc.
  ansible.builtin.apt_repository:
    repo: deb http://ppa.launchpad.net/ansible/ansible/ubuntu bionic main
    filename: launchpad-ppa-ansible-ansible

- name: Install Ansible
  jm1.pkg.meta_pkg:
    name: "jm1-packages-ansible"
    version: "8"
    depends:
    - ansible (>= 2.9.0)
    # pip is required for Ansible's pip module
    - python-pip
    - python3-pip
    # Python module netaddr is required for Ansible's ipaddr filter
    - python-netaddr
    - python3-netaddr
    # Python module libvirt is required for Ansible's virt* modules
    - python-libvirt
    - python3-libvirt
    # setfacl tool is used to set permissions on temporary files when becoming an unprivileged user
    # Ref.: https://stackoverflow.com/questions/46352173/ansible-failed-to-set-permissions-on-the-temporary#comment116424403_56379678
    - acl
    # Python module pyghmi is required for Ansible's ipmi_* modules
    - python-pyghmi
    - python3-pyghmi

- name: Install Python modules for Ansible
  pip:
    name:
    # Pyhton module zabbix-api is required for Ansible's zabbix_* modules
    - zabbix-api
    executable: '{{ item }}'
  # Install packages for Python 2 and 3, because Ansible might be executed with both interpreters
  loop:
  - pip2
  - pip3
