---
# Copyright (c) 2024 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

- name: Install libvirt daemon, clients, tools and libraries to manage KVM/QEMU virtual machines
  jm1.pkg.meta_pkg:
    name: "jm1-packages-libvirt-qemu"
    version: "1"
    depends:
    - jm1-libvirt-setup
    - libguestfs
    - libvirt-client
    - libvirt-daemon
    - libvirt-daemon-config-network
    - libvirt-daemon-kvm
    - virt-install
    - qemu-kvm
    - qemu-img
