---
# Copyright (c) 2020-2022 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

- name: Enable yum repositories for Extra Packages for Enterprise Linux (EPEL)
  import_role:
    name: jm1.pkg.yum_repository
  vars:
    yum_repository_config: '{{ yum_repository_config_epel }}'

- name: Install libvirt daemon, clients, tools and libraries to manage KVM/QEMU virtual machines
  when: distribution_id|last in ['7', '8']
  jm1.pkg.meta_pkg:
    name: "jm1-packages-libvirt-qemu"
    version: "2"
    depends:
    - jm1-libvirt-setup
    - libguestfs
    - libvirt-client
    - libvirt-daemon
    - libvirt-daemon-config-network
    - libvirt-daemon-kvm
    - virt-install
    - virt-top
    - qemu-kvm
    - qemu-img
