---
# Copyright (c) 2020-2021 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

# Tasks for Debian and Ubuntu have been unified in a single file because of similarities between both distributions.

- name: Install libvirt daemon, clients, tools and libraries to manage KVM/QEMU virtual machines
  jm1.pkg.meta_pkg:
    name: "jm1-packages-libvirt-qemu"
    version: "3"
    depends:
    - jm1-libvirt-setup
    - libvirt-clients
    - libvirt-daemon
    - libvirt-daemon-system
    - libvirt-daemon-driver-storage-rbd
    - virtinst
    - qemu-kvm
    conflicts:
    - qemu-system-gui # Do not install qemu-system-gui, because this will pull in a lot of desktop related packages.
