---
# Copyright (c) 2020-2021 Jakob Meng, <jakobmeng@web.de>
# vim:set fileformat=unix tabstop=2 shiftwidth=2 expandtab:
# kate: end-of-line unix; space-indent on; indent-width 2; remove-trailing-spaces modified;

# Extra Packages for Enterprise Linux (EPEL) repository is enabled already by role jm1.pkg.setup

- name: Install libvirt daemon, clients, tools and libraries to manage KVM/QEMU virtual machines
  when: distribution_id|last in ['7', '8']
  jm1.pkg.meta_pkg:
    name: "jm1-packages-libvirt-qemu"
    version: "1"
    depends:
    - jm1-libvirt-setup
    - libvirt-client
    - libvirt-daemon
    - libvirt-daemon-driver-storage-rbd
    - virt-install
    - virt-top
    - qemu-kvm
    - qemu-img
